const dataProducts = {
  data: [
    {
      code: "11515502",
      product_name: "Possimus repellendus error.",
      product_description:
        "Ut quia tempore ut voluptatum ea quas. Sed quas iure sint quia consequatur amet recusandae.",
      product_price: "899.78",
      product_quantity: 14,
      status: 1,
      product_size: "S",
      product_brand: "Bruen, Bahringer and Waelchi",
      category: {
        name: "Books",
        slug: "books",
        status: "Active",
        url: "http://ecommerce.test/api/category/books",
        products_count: 18,
      },
      date: "2021-02-17",
    },
    {
      code: "89736179",
      product_name: "Eligendi quod harum voluptatem.",
      product_description:
        "Necessitatibus maxime adipisci ut nihil vero dolorum. Nihil voluptatibus mollitia molestias unde. Facilis rerum sed voluptatum sunt omnis voluptatem. Quod occaecati ea ipsum incidunt. Consequatur ea ipsa incidunt adipisci molestias labore. Delectus consequuntur occaecati esse dolorem et debitis. Deleniti eligendi dolorem natus molestias quia.",
      product_price: "453.92",
      product_quantity: 61,
      status: 1,
      product_size: "L",
      product_brand: "Gerlach-Romaguera",
      category: {
        name: "Fashion",
        slug: "fashion",
        status: "Active",
        url: "http://ecommerce.test/api/category/fashion",
        products_count: 13,
      },
      date: "1975-10-02",
    },
    {
      code: "37549190",
      product_name: "Esse dignissimos non ratione sint consequatur culpa.",
      product_description:
        "Enim dolorum mollitia cupiditate quam maiores nemo. Esse dolor architecto hic ducimus et delectus. Quae consequuntur voluptate similique nam.",
      product_price: "895.82",
      product_quantity: 2,
      status: 1,
      product_size: "L",
      product_brand: "Goodwin, Howell and Rogahn",
      category: {
        name: "Health & Beauty",
        slug: "health-beauty",
        status: "Active",
        url: "http://ecommerce.test/api/category/health-beauty",
        products_count: 11,
      },
      date: "2006-07-01",
    },
    {
      code: "50091486",
      product_name: "Velit earum voluptatem iure.",
      product_description:
        "Aut aut et iure voluptatum. Similique ad molestiae ullam nemo corrupti fugiat. Aut sapiente maiores voluptatem. Odio omnis sed ex quia possimus nostrum et. Ullam quibusdam minus quisquam explicabo. Omnis et magnam sit.",
      product_price: "702.02",
      product_quantity: 9,
      status: 1,
      product_size: "L",
      product_brand: "Adams PLC",
      category: {
        name: "Books",
        slug: "books",
        status: "Active",
        url: "http://ecommerce.test/api/category/books",
        products_count: 18,
      },
      date: "2012-07-15",
    },
    {
      code: "37460640",
      product_name:
        "Debitis enim est necessitatibus repudiandae exercitationem dolorem soluta.",
      product_description:
        "Eos totam quasi quod sint ut dolor vel ratione. Quibusdam rerum iste eveniet molestias. Tempore enim deserunt vel earum sequi magnam exercitationem.",
      product_price: "90.44",
      product_quantity: 64,
      status: 1,
      product_size: "L",
      product_brand: "Daniel, Eichmann and Wilderman",
      category: {
        name: "Electronic",
        slug: "electronic",
        status: "Active",
        url: "http://ecommerce.test/api/category/electronic",
        products_count: 17,
      },
      date: "2013-02-26",
    },
    {
      code: "26986299",
      product_name: "Ipsum eum atque non ullam.",
      product_description:
        "Eligendi nam repudiandae quo id in rerum deserunt. Eos illum veniam voluptates eos. Deserunt nesciunt eaque recusandae dignissimos qui. Quam praesentium animi exercitationem culpa iste quisquam.",
      product_price: "596.27",
      product_quantity: 4,
      status: 1,
      product_size: "L",
      product_brand: "Orn and Sons",
      category: {
        name: "Electronic",
        slug: "electronic",
        status: "Active",
        url: "http://ecommerce.test/api/category/electronic",
        products_count: 17,
      },
      date: "1994-07-27",
    },
    {
      code: "77279519",
      product_name: "Repudiandae eveniet labore ut.",
      product_description:
        "Officia sed voluptatem natus non. Consequatur soluta vel in vitae eligendi accusamus. Vel laudantium iusto eum et. Placeat sunt non omnis. Dignissimos est voluptas voluptatem deleniti necessitatibus. Nostrum deserunt praesentium sint quia et atque quisquam. Ut et rem dolore aut fugiat. Sint nobis eum rerum laborum.",
      product_price: "111.77",
      product_quantity: 65,
      status: 1,
      product_size: "XL",
      product_brand: "Keeling PLC",
      category: {
        name: "Books",
        slug: "books",
        status: "Active",
        url: "http://ecommerce.test/api/category/books",
        products_count: 18,
      },
      date: "1998-12-22",
    },
    {
      code: "2936161",
      product_name: "Harum laborum laudantium inventore natus.",
      product_description:
        "Sit expedita omnis est omnis. Quo ea eaque error sit repudiandae saepe. Fugit sunt quia maiores perspiciatis. Sit eos aut aut voluptatem. Nostrum unde doloremque consequatur dolor. In accusamus quia libero voluptatibus nulla.",
      product_price: "324.02",
      product_quantity: 53,
      status: 1,
      product_size: "M",
      product_brand: "Aufderhar-Kertzmann",
      category: {
        name: "Fashion",
        slug: "fashion",
        status: "Active",
        url: "http://ecommerce.test/api/category/fashion",
        products_count: 13,
      },
      date: "1986-07-11",
    },
    {
      code: "39653948",
      product_name: "Sequi omnis rerum soluta.",
      product_description:
        "Harum nemo dolor enim eveniet minus. Eum odit ex est nostrum qui sit. Tempora est exercitationem et sit. Voluptatem labore doloribus et iusto asperiores officiis. Aut ipsa non dolor nisi. Ipsa maxime tempora et fugiat qui dolores.",
      product_price: "510.82",
      product_quantity: 23,
      status: 1,
      product_size: "M",
      product_brand: "Schuster Group",
      category: {
        name: "Electronic",
        slug: "electronic",
        status: "Active",
        url: "http://ecommerce.test/api/category/electronic",
        products_count: 17,
      },
      date: "1999-04-21",
    },
    {
      code: "89493583",
      product_name: "Dolore ad illo repellat similique rerum voluptas.",
      product_description:
        "Repudiandae praesentium atque beatae dignissimos itaque. Ratione quis autem odit magni eos. Natus doloribus in quisquam ea voluptatum placeat pariatur soluta. Libero delectus ullam corrupti pariatur hic. Error praesentium quia quasi quis omnis suscipit. Odio earum repellendus sint et aspernatur autem. Et tempora similique explicabo velit dolorem cum labore.",
      product_price: "112.91",
      product_quantity: 13,
      status: 1,
      product_size: "S",
      product_brand: "Nitzsche Inc",
      category: {
        name: "Electronic",
        slug: "electronic",
        status: "Active",
        url: "http://ecommerce.test/api/category/electronic",
        products_count: 17,
      },
      date: "1971-06-14",
    },
  ],
  links: {
    first: "http://ecommerce.test/api/all_products?page=1",
    last: "http://ecommerce.test/api/all_products?page=6",
    prev: null,
    next: "http://ecommerce.test/api/all_products?page=2",
  },
  meta: {
    current_page: 1,
    from: 1,
    last_page: 6,
    links: [
      {
        url: null,
        label: "&laquo; Previous",
        active: false,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=1",
        label: "1",
        active: true,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=2",
        label: "2",
        active: false,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=3",
        label: "3",
        active: false,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=4",
        label: "4",
        active: false,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=5",
        label: "5",
        active: false,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=6",
        label: "6",
        active: false,
      },
      {
        url: "http://ecommerce.test/api/all_products?page=2",
        label: "Next &raquo;",
        active: false,
      },
    ],
    path: "http://ecommerce.test/api/all_products",
    per_page: 10,
    to: 10,
    total: 59,
  },
};
